# Generated by Django 5.2.1 on 2025-06-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_cliente_cnpj_cliente_cpf_cliente_inscricao_estadual_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='criado_em',
            new_name='data_pedido',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='finalizado',
        ),
        migrations.AddField(
            model_name='pedido',
            name='codigo_rastreamento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('aguardando', 'Aguardando Pagamento'), ('processando', 'Processando'), ('enviado', 'Enviado'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='aguardando', max_length=20),
        ),
    ]
