# Generated by Django 5.2.1 on 2025-07-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_rename_criado_em_pedido_data_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='codigo_rastreamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
